# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1842, 936)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(60, 40, 1531, 571))
        self.MplWidget.setObjectName("MplWidget")
        self.comboBoxCountry = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCountry.setGeometry(QtCore.QRect(50, 640, 271, 22))
        self.comboBoxCountry.setObjectName("comboBoxCountry")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 620, 171, 16))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(610, 720, 121, 131))
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.radioButtonCasos = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonCasos.setGeometry(QtCore.QRect(20, 30, 95, 20))
        self.radioButtonCasos.setCheckable(True)
        self.radioButtonCasos.setChecked(False)
        self.radioButtonCasos.setObjectName("radioButtonCasos")
        self.radioButtonMuertes = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonMuertes.setGeometry(QtCore.QRect(20, 60, 95, 20))
        self.radioButtonMuertes.setCheckable(True)
        self.radioButtonMuertes.setChecked(False)
        self.radioButtonMuertes.setObjectName("radioButtonMuertes")
        self.radioButtonAmbos = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonAmbos.setGeometry(QtCore.QRect(20, 90, 95, 20))
        self.radioButtonAmbos.setCheckable(True)
        self.radioButtonAmbos.setChecked(True)
        self.radioButtonAmbos.setObjectName("radioButtonAmbos")
        self.comboBoxEstado = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxEstado.setGeometry(QtCore.QRect(350, 640, 221, 22))
        self.comboBoxEstado.setObjectName("comboBoxEstado")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 620, 171, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(760, 720, 120, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButtonDiarios = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonDiarios.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.radioButtonDiarios.setObjectName("radioButtonDiarios")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 95, 20))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.sliderPromedio = QtWidgets.QSlider(self.centralwidget)
        self.sliderPromedio.setGeometry(QtCore.QRect(700, 640, 251, 22))
        self.sliderPromedio.setMinimum(0)
        self.sliderPromedio.setMaximum(15)
        self.sliderPromedio.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPromedio.setObjectName("sliderPromedio")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 640, 101, 16))
        self.label_3.setObjectName("label_3")
        self.tableWidgetCovid = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetCovid.setGeometry(QtCore.QRect(1160, 640, 401, 221))
        self.tableWidgetCovid.setObjectName("tableWidgetCovid")
        self.tableWidgetCovid.setColumnCount(3)
        self.tableWidgetCovid.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCovid.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCovid.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCovid.setHorizontalHeaderItem(2, item)
        self.lcdNumberSlider = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberSlider.setGeometry(QtCore.QRect(990, 630, 91, 51))
        self.lcdNumberSlider.setObjectName("lcdNumberSlider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1842, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Seleccione un pais:"))
        self.groupBox.setTitle(_translate("MainWindow", "Seleccionar"))
        self.radioButtonCasos.setText(_translate("MainWindow", "Casos"))
        self.radioButtonMuertes.setText(_translate("MainWindow", "Muertes"))
        self.radioButtonAmbos.setText(_translate("MainWindow", "Ambos"))
        self.label_2.setText(_translate("MainWindow", "Seleccione estado:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Seleccionar"))
        self.radioButtonDiarios.setText(_translate("MainWindow", "Diarios"))
        self.radioButton_2.setText(_translate("MainWindow", "Acumulados"))
        self.label_3.setText(_translate("MainWindow", "Promedio:"))
        item = self.tableWidgetCovid.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tableWidgetCovid.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Casos"))
        item = self.tableWidgetCovid.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Muertes"))


from mplwidget import MplWidget

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
